name: Tests

on: [push]

jobs:
  all:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.build-matrix.outputs.languages }}
    steps:
      - uses: actions/checkout@v2
      - name: discover all examples
        id: build-matrix
        run: node .github/generate-test-steps.js >> "$GITHUB_OUTPUT"
  
  javascript:
    needs: all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJSON(needs.all.outputs.languages).javascript }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'
      - name: test setup
        run: ${{ matrix.example.preTestCommands }}
        working-directory: javascript/${{ matrix.example.name }}
        if: matrix.example.preTestCommands != null
      - name: test
        run: ${{ matrix.example.testCommands }}
        working-directory: javascript/${{ matrix.example.name }}

  kotlin:
    needs: all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJSON(needs.all.outputs.languages).kotlin }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: test setup
        run: ${{ matrix.example.preTestCommands }}
        working-directory: kotlin/${{ matrix.example.name }}
        if: matrix.example.preTestCommands != null
      - name: test in android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ${{ matrix.example.testCommands }}
          working-directory: kotlin/${{ matrix.example.name }}
